language: c
compiler:
  - gcc
branches:
  only:
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade
  - sudo apt-get update
  - sudo apt-get install libstdc++6
script: ./build_tests.sh
notifications:
  slack: ifj-projectgroup:wgciDeWTSoYEwi38yhSV9rpE